services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    env_file: .env.prod
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./ai-snippet-web
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3030:3030'
    env_file: .env
    environment:
      - VITE_API_BASE_URL=http://backend:3000
    depends_on:
      - backend
